// <auto-generated />
using System;
using AccessControl.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessControl.Server.Migrations
{
    [DbContext(typeof(AccessControlSystemDataContext))]
    [Migration("20250908233658_primeiravercao")]
    partial class primeiravercao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AccessControl.Server.Models.AccessRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessRule");
                });

            modelBuilder.Entity("AccessControl.Server.Models.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("AccessControl.Server.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdDevice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("AccessControl.Server.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FridayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FridayStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MondayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MondayStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaturdayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaturdayStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SundayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SundayStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThursdayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThursdayStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuesdayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TuesdayStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WednesdayEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WednesdayStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("AccessControl.Server.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("Card")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataLastLog")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEndLimit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStartLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Pin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AccessRuleDevice", b =>
                {
                    b.Property<long>("AccessRulesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DevicesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessRulesId", "DevicesId");

                    b.HasIndex("DevicesId");

                    b.ToTable("AccessRuleDevice");
                });

            modelBuilder.Entity("AccessRuleSchedule", b =>
                {
                    b.Property<long>("AccessRulesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SchedulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessRulesId", "SchedulesId");

                    b.HasIndex("SchedulesId");

                    b.ToTable("AccessRuleSchedule");
                });

            modelBuilder.Entity("AccessRuleUser", b =>
                {
                    b.Property<long>("AccessRulesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessRulesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AccessRuleUser");
                });

            modelBuilder.Entity("AccessRuleDevice", b =>
                {
                    b.HasOne("AccessControl.Server.Models.AccessRule", null)
                        .WithMany()
                        .HasForeignKey("AccessRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Server.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessRuleSchedule", b =>
                {
                    b.HasOne("AccessControl.Server.Models.AccessRule", null)
                        .WithMany()
                        .HasForeignKey("AccessRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Server.Models.Schedule", null)
                        .WithMany()
                        .HasForeignKey("SchedulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessRuleUser", b =>
                {
                    b.HasOne("AccessControl.Server.Models.AccessRule", null)
                        .WithMany()
                        .HasForeignKey("AccessRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
